[Feat] UserBook 생성, 상태변경, 삭제 기능
MoneyMakersClub/mmc-backend pull request #9
Opened 2024-10-09 05:25 UTC by hyejin2234

# 구현 기능
  - UserBook (서재 책) 추가, 상태변경, 삭제 기능을 개발했습니다.
  - userbook을 생성하기 전에 bookInfo를 먼저 생성하도록 개발했습니다.
  - userBook 엔티티에 bookInfo 연관관계를 추가했습니다.

# Resolve
  - #8

2024-10-09 06:01 UTC, seohyun-lee commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +    public UserBookResponseDto addUserBook(@RequestBody UserBookRequestDto dto,
상태코드를 위해 ResponseEntity<?> 사용 부탁드려요!

2024-10-09 06:01 UTC, seohyun-lee commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +        return userBookService.updateUserBookStatus(userBookId, status);
@PathVariable들, @RequestParam들에 final 붙여주세요!

2024-10-09 10:49 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +    public UserBookResponseDto addUserBook(@RequestBody UserBookRequestDto dto,
> 상태코드를 위해 ResponseEntity<?> 사용 부탁드려요!

ResponseEntity로 수정완료했습니다!

2024-10-09 10:50 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +        return userBookService.updateUserBookStatus(userBookId, status);
> @PathVariable들, @RequestParam들에 final 붙여주세요!

수정했습니다!

2024-10-09 11:54 UTC, jud1thDev requested changes

2024-10-09 11:54 UTC, jud1thDev commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +@Service
Transactional 이 위치에 붙여도 좋을 것 같아요!

2024-10-09 11:54 UTC, jud1thDev commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        UserBook userBook = UserBook.builder()
dto에 toEntity사용해서 코드 리팩토링 하면 좋을 것 같아요

```
    UserBook userBook = dto.toEntity(findUser(), bookInfo);
    UserBook savedUserBook = userBookRepository.save(userBook);
    return UserBookResponseDto.from(savedUserBook);
```

2024-10-09 11:54 UTC, jud1thDev commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        if(userBook.getUser().getUserId() == userId){
equals로 변경

2024-10-09 11:54 UTC, jud1thDev commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +            return new UserBookResponseDto(userBook.getUserBookId(), userBook.getBookInfo().getTitle(), userBook.getBookInfo().getAuthor(),
생성 로직 DTO로 분리 (from메서드)

2024-10-09 11:54 UTC, jud1thDev commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
> +    List<UserBook> searchByUserIdAndKeyword(@Param("user") User user, @Param("keyword") String keyword);
검색을 userId필드만으로 한다면 @Param("userId") 로 변겨

2024-10-09 14:41 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +@Service
수정했습니다

2024-10-09 14:42 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        UserBook userBook = UserBook.builder()
toEntity 생성해서 수정완료했습니다!

2024-10-09 14:42 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        if(userBook.getUser().getUserId() == userId){
equals로 수정했습니다!

2024-10-09 14:43 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +            return new UserBookResponseDto(userBook.getUserBookId(), userBook.getBookInfo().getTitle(), userBook.getBookInfo().getAuthor(),
form으로 수정했습니다!

2024-10-09 14:43 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
> +    List<UserBook> searchByUserIdAndKeyword(@Param("user") User user, @Param("keyword") String keyword);
수정완료했습니다!

2024-10-11 01:29 UTC, seohyun-lee reviewed
코멘트 남겼습니다!

2024-10-11 01:29 UTC, seohyun-lee commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
> +    UserBook findByUserAndBookInfo(User user, BookInfo bookInfo);
여기도 Optional을 쓰면 좋을 것 같아요. 안 사용하신 이유가 있으실까요?

2024-10-11 01:29 UTC, seohyun-lee commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +                                                           @RequestParam(name="status") final String status){
UserBookRequestDto안에 status를 안 넣으신 이유가 있을까요?

2024-10-11 01:29 UTC, seohyun-lee commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        UserBook userBook = userBookRepository.findById(userBookId)
Userbook을 찾는 메소드들이 중복되는데 하나 따로 만들어 두시고 호출하시는 게 좋을 것 같습니다!!

2024-10-11 04:03 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
> +        UserBook userBook = userBookRepository.findById(userBookId)
수정했습니다!

2024-10-11 05:28 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
> +    UserBook findByUserAndBookInfo(User user, BookInfo bookInfo);
딱히 사용하지 않은 이유는 없습니닷.. service에서 null 체크를 하는 걸로 했었는데 Optional로 수정했습니다!

2024-10-11 05:28 UTC, hyejin2234 commented on bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/UserBookController.java
> +                                                           @RequestParam(name="status") final String status){
이것도 수정했습니다!

2024-10-11 11:16 UTC, merged